# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Parizot
description:      'Multimedia journalist for any occaision '
baseurl:          /

# pagination
paginate:         5

# Hyde theme
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

exclude: ["node_modules", "gulpfile.js", "package.json"]
