# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Parizot
description:      'Add a description here'
baseurl:          /

# pagination
paginate:         5

# Hyde theme
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
  
exclude: ["node_modules", "gulpfile.js", "package.json"]